spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:mariadb://54.251.197.30:3306/profile_service
    username: root
    password: fred
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://18.140.1.2:8761/eureka
    register-with-eureka: true
    fetch-registry: true

mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.a2m.profileservice.model

server:
  port: 8888

springdoc:
  api-docs:
    enabled: true  # Bật API docs
    path: /v3/api-docs  # Đặt đường dẫn API docs
  swagger-ui:
    enabled: true  # Bật Swagger UI
    path: /swagger-ui.html  # Đặt đường dẫn Swagger UI
